module.exports=function(sequelize,DataType){
    return sequelize.define(
        'proxy',
        {
            schema:{
                type:DataType.STRING,
                allowNull:false,
                comment:'schema，目前仅支持http/https，小写'
            },
            ip:{
                type:DataType.STRING,
                allowNull:false,
                comment:"ip地址或者域名",
            },
            port:{
                type:DataType.STRING,
                allowNull:false,
                comment:'端口号',
            },
            comeFrom:{
                type:DataType.STRING,
                allowNull:true,
                comment:'采集自于哪个代理网站',
            },
        },
        {
            tableName:'proxy',
            indexes:[
                {unique:true,fields:['schema','ip','port']}
            ],
        }
    );
};